### ISSUE TITLE
UnwrapTrim crashes on first class callable syntax

### ISSUE THREAD

**Issue by erikgaal** [pestphp/pest-plugin-mutate#4]
UnwrapTrim crashes when using first class callable syntax in code.

The source code it crashes on looks something like this:
```php
public static function fromString(string $value): self
{
    $lines = array_map(trim(...), explode(',', $value));

    return;
}
```

Using mutate plugin version `v2.0.0-beta.3`.

<details>
<summary>Backtrace</summary>

```
  Running initial test suite:  

  ...................................................................................................................................................................................................................................................................................................

  Tests:    291 passed (380 assertions)
  Duration: 13.14s

  Generating mutations ...

   WARN  Exception in third-party event subscriber: Pest\Mutate\Mutators\Abstract\AbstractFunctionCallUnwrapMutator::mutate(): Return value must be of type PhpParser\Node, null returned
#0 /project/vendor/pestphp/pest-plugin-mutate/src/Support/NodeVisitor.php(77): Pest\Mutate\Mutators\Abstract\AbstractFunctionCallUnwrapMutator::mutate(Object(PhpParser\Node\Expr\FuncCall))
#1 /project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(153): Pest\Mutate\Support\NodeVisitor->leaveNode(Object(PhpParser\Node\Expr\FuncCall))
#2 /project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Arg))
#3 /project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#4 /project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\FuncCall))
#5 /project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))
#6 /project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#7 /project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#8 /project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#9 /project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#10 /project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#11 /project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#12 /project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#13 /project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#14 /project/vendor/pestphp/pest-plugin-mutate/src/Support/MutationGenerator.php(88): PhpParser\NodeTraverser->traverse(Array)
#15 /project/vendor/pestphp/pest-plugin-mutate/src/Tester/MutationTestRunner.php(152): Pest\Mutate\Support\MutationGenerator->generate(Object(Symfony\Component\Finder\SplFileInfo), Array, Array, Array)
#16 /project/vendor/pestphp/pest-plugin-mutate/src/Subscribers/EnsureToRunMutationTestingIfRequired.php(26): Pest\Mutate\Tester\MutationTestRunner->run()
#17 /project/vendor/phpunit/phpunit/src/Event/Dispatcher/DirectDispatcher.php(102): Pest\Mutate\Subscribers\EnsureToRunMutationTestingIfRequired->notify(Object(PHPUnit\Event\Application\Finished))
#18 /project/vendor/phpunit/phpunit/src/Event/Dispatcher/DeferringDispatcher.php(45): PHPUnit\Event\DirectDispatcher->dispatch(Object(PHPUnit\Event\Application\Finished))
#19 /project/vendor/phpunit/phpunit/src/Event/Emitter/DispatchingEmitter.php(1201): PHPUnit\Event\DeferringDispatcher->dispatch(Object(PHPUnit\Event\Application\Finished))
#20 /project/vendor/phpunit/phpunit/src/TextUI/Application.php(259): PHPUnit\Event\DispatchingEmitter->applicationFinished(0)
#21 /project/vendor/pestphp/pest/src/Kernel.php(103): PHPUnit\TextUI\Application->run(Array)
#22 /project/vendor/pestphp/pest/bin/pest(91): Pest\Kernel->handle(Array, Array)
#23 /project/vendor/pestphp/pest/bin/pest(99): {closure}()
#24 /project/vendor/bin/pest(119): include('/Users/erik.gaa...')
#25 {main}

   INFO  Warning: Undefined property: PhpParser\Node\VariadicPlaceholder::$value in /project/vendor/pestphp/pest-plugin-mutate/src/Mutators/Abstract/AbstractFunctionCallUnwrapMutator.php on line 34.
```

</details>

**Comment by gehrisandro** [comment]
Hi @erikgaal 

Thank you. I will check and fix this later today.

**Comment by gehrisandro** [comment]
Hi @erikgaal 

Fixed in the new release: https://github.com/pestphp/pest-plugin-mutate/releases/tag/v2.0.0-beta.4

Thanks again for reporting the issue.
If you have any other feedback, please let us know. 👀

**Comment by erikgaal** [comment]
Amazing! Thank you!
