### ISSUE TITLE
Argument #1 ($tests) must be of type array, null given

### ISSUE THREAD

**Issue by Rasmus-Bertell** [pestphp/pest-plugin-mutate#6]
Trying to run `./vendor/bin/pest --mutate` produces the following error.
It might be because of something I did since it worked a couple of days ago.

```text
❯ ./vendor/bin/pest --mutate

  Running initial test suite:  

  ...

  Tests:    3 passed (3 assertions)
  Duration: 0.95s

  Generating mutations ...

   WARN  Exception in third-party event subscriber: Pest\Mutate\Tester\MutationTestRunner::Pest\Mutate\Tester\{closure}(): Argument #1 ($tests) must be of type array, null given
#0 [internal function]: Pest\Mutate\Tester\MutationTestRunner->Pest\Mutate\Tester\{closure}()
#1 /home/rasmus/projects/xxxxxxxxxxxxxxxxx/vendor/pestphp/pest-plugin-mutate/src/Tester/MutationTestRunner.php(111): array_filter()
#2 [internal function]: Pest\Mutate\Tester\MutationTestRunner->Pest\Mutate\Tester\{closure}()
#3 /home/rasmus/projects/xxxxxxxxxxxxxxxxx/vendor/pestphp/pest-plugin-mutate/src/Tester/MutationTestRunner.php(111): array_map()
#4 /home/rasmus/projects/xxxxxxxxxxxxxxxxx/vendor/pestphp/pest-plugin-mutate/src/Subscribers/EnsureToRunMutationTestingIfRequired.php(26): Pest\Mutate\Tester\MutationTestRunner->run()
#5 /home/rasmus/projects/xxxxxxxxxxxxxxxxx/vendor/phpunit/phpunit/src/Event/Dispatcher/DirectDispatcher.php(102): Pest\Mutate\Subscribers\EnsureToRunMutationTestingIfRequired->notify()
#6 /home/rasmus/projects/xxxxxxxxxxxxxxxxx/vendor/phpunit/phpunit/src/Event/Dispatcher/DeferringDispatcher.php(45): PHPUnit\Event\DirectDispatcher->dispatch()
#7 /home/rasmus/projects/xxxxxxxxxxxxxxxxx/vendor/phpunit/phpunit/src/Event/Emitter/DispatchingEmitter.php(1201): PHPUnit\Event\DeferringDispatcher->dispatch()
#8 /home/rasmus/projects/xxxxxxxxxxxxxxxxx/vendor/phpunit/phpunit/src/TextUI/Application.php(259): PHPUnit\Event\DispatchingEmitter->applicationFinished()
#9 /home/rasmus/projects/xxxxxxxxxxxxxxxxx/vendor/pestphp/pest/src/Kernel.php(103): PHPUnit\TextUI\Application->run()
#10 /home/rasmus/projects/xxxxxxxxxxxxxxxxx/vendor/pestphp/pest/bin/pest(91): Pest\Kernel->handle()
#11 /home/rasmus/projects/xxxxxxxxxxxxxxxxx/vendor/pestphp/pest/bin/pest(99): {closure}()
#12 /home/rasmus/projects/xxxxxxxxxxxxxxxxx/vendor/bin/pest(119): include('...')
#13 {main}
```

Decided to look closer at the error and seems like there are some unexpected null lines in the code coverage report

```text

array:9 [
  "/home/rasmus/projects/xxxxxxxxxxxxxxxxx/app/Http/Controllers/Controller.php" => []
  "/home/rasmus/projects/xxxxxxxxxxxxxxxxx/app/Http/Controllers/LocaleController.php" => array:7 [
    17 => []
    25 => []
    33 => []
    41 => []
    49 => []
    57 => []
    65 => []
  ]
  "/home/rasmus/projects/xxxxxxxxxxxxxxxxx/app/Http/Middleware/EnsureLocaleIsValid.php" => array:30 [
    15 => array:2 [
      0 => "P\Tests\Feature\EnsureLocaleIsValidTest::__pest_evaluable_it_sets_the_locale_from_the_request_if_it_is_valid"
      1 => "P\Tests\Feature\Test::__pest_evaluable_it_has__page"
    ]
    17 => array:2 [
      0 => "P\Tests\Feature\EnsureLocaleIsValidTest::__pest_evaluable_it_sets_the_locale_from_the_request_if_it_is_valid"
      1 => "P\Tests\Feature\Test::__pest_evaluable_it_has__page"
    ]
    18 => array:1 [
      0 => "P\Tests\Feature\EnsureLocaleIsValidTest::__pest_evaluable_it_sets_the_locale_from_the_request_if_it_is_valid"
    ]
    21 => array:2 [
      0 => "P\Tests\Feature\EnsureLocaleIsValidTest::__pest_evaluable_it_sets_the_locale_from_the_request_if_it_is_valid"
      1 => "P\Tests\Feature\Test::__pest_evaluable_it_has__page"
    ]
    23 => null
    25 => null
    26 => []
    27 => []
    28 => []
    29 => []
    30 => []
    31 => []
    33 => null
    34 => null
    36 => null
    41 => null
    42 => null
    43 => null
    45 => null
    47 => null
    49 => null
    54 => array:1 [
      0 => "P\Tests\Feature\Test::__pest_evaluable_it_has__page"
    ]
    56 => array:1 [
      0 => "P\Tests\Feature\Test::__pest_evaluable_it_has__page"
    ]
    57 => array:1 [
      0 => "P\Tests\Feature\Test::__pest_evaluable_it_has__page"
    ]
    60 => []
    61 => []
    62 => []
    63 => []
    64 => []
    65 => []
  ]
  "/home/rasmus/projects/xxxxxxxxxxxxxxxxx/app/Http/Requests/StoreLocaleRequest.php" => array:4 [
    14 => []
    24 => []
    25 => []
    26 => []
  ]
  "/home/rasmus/projects/xxxxxxxxxxxxxxxxx/app/Http/Requests/UpdateLocaleRequest.php" => array:4 [
    14 => []
    24 => []
    25 => []
    26 => []
  ]
  "/home/rasmus/projects/xxxxxxxxxxxxxxxxx/app/Models/Locale.php" => array:9 [
    26 => []
    27 => []
    30 => []
    31 => []
    32 => []
    34 => []
    35 => []
    38 => []
    43 => []
  ]
  "/home/rasmus/projects/xxxxxxxxxxxxxxxxx/app/Models/User.php" => array:4 [
    49 => []
    50 => []
    51 => []
    52 => []
  ]
  "/home/rasmus/projects/xxxxxxxxxxxxxxxxx/app/Policies/LocalePolicy.php" => array:7 [
    16 => []
    24 => []
    32 => []
    40 => []
    48 => []
    56 => []
    64 => []
  ]
  "/home/rasmus/projects/xxxxxxxxxxxxxxxxx/app/Providers/AppServiceProvider.php" => array:2 [
    15 => array:2 [
      0 => "P\Tests\Feature\EnsureLocaleIsValidTest::__pest_evaluable_it_sets_the_locale_from_the_request_if_it_is_valid"
      1 => "P\Tests\Feature\Test::__pest_evaluable_it_has__page"
    ]
    23 => array:2 [
      0 => "P\Tests\Feature\EnsureLocaleIsValidTest::__pest_evaluable_it_sets_the_locale_from_the_request_if_it_is_valid"
      1 => "P\Tests\Feature\Test::__pest_evaluable_it_has__page"
    ]
  ]
]
```

Tested that changing the line 111 like this solves the issue.

```diff
-        $coveredLines = array_map(fn (array $lines): array => array_filter($lines, fn (array $tests): bool => $tests !== []), $codeCoverage->getData()->lineCoverage());
+        $coveredLines = array_map(fn (array $lines): array => array_filter($lines, fn (?array $tests): bool => !empty($tests)), $codeCoverage->getData()->lineCoverage());
```

**Comment by gehrisandro** [comment]
Hi @Rasmus-Bertell 

Thank you for your report and your PR.

Can you tell me which PHP version and version of `phpunit/php-code-coverage`you have installed?
Command: `composer show phpunit/php-code-coverage`

And have you upgraded any other packages or the PHP version lately?

**Comment by Rasmus-Bertell** [comment]
I don't recall making any changes to the packages other than configuring phpstan, pint and pest.

```sh
 php -v
PHP 8.3.10 (cli) (built: Jul 31 2024 13:54:49) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.10, Copyright (c) Zend Technologies
    with Xdebug v3.3.2, Copyright (c) 2002-2024, by Derick Rethans

 composer show phpunit/php-code-coverage
name     : phpunit/php-code-coverage
descrip. : Library that provides collection, processing, and rendering functionality for PHP code coverage information.
keywords : coverage, testing, xunit
versions : * 10.1.15
released : 2024-06-29, 1 month ago
type     : library
license  : BSD 3-Clause "New" or "Revised" License (BSD-3-Clause) (OSI approved) https://spdx.org/licenses/BSD-3-Clause.html#licenseText
homepage : https://github.com/sebastianbergmann/php-code-coverage
source   : [git] https://github.com/sebastianbergmann/php-code-coverage.git 5da8b1728acd1e6ffdf2ff32ffbdfd04307f26ae
dist     : [zip] https://api.github.com/repos/sebastianbergmann/php-code-coverage/zipball/5da8b1728acd1e6ffdf2ff32ffbdfd04307f26ae 5da8b1728acd1e6ffdf2ff32ffbdfd04307f26ae
path     : /home/rasmus/projects/xxxxxxxxxxxxxxxxx/vendor/phpunit/php-code-coverage
names    : phpunit/php-code-coverage

support
issues : https://github.com/sebastianbergmann/php-code-coverage/issues
security : https://github.com/sebastianbergmann/php-code-coverage/security/policy
source : https://github.com/sebastianbergmann/php-code-coverage/tree/10.1.15

autoload
classmap
src/

requires
ext-dom *
ext-libxml *
ext-xmlwriter *
nikic/php-parser ^4.18 || ^5.0
php >=8.1
phpunit/php-file-iterator ^4.0
phpunit/php-text-template ^3.0
sebastian/code-unit-reverse-lookup ^3.0
sebastian/complexity ^3.0
sebastian/environment ^6.0
sebastian/lines-of-code ^2.0
sebastian/version ^4.0
theseer/tokenizer ^1.2.0

requires (dev)
phpunit/phpunit ^10.1

suggests
ext-pcov PHP extension that provides line coverage
ext-xdebug PHP extension that provides line coverage as well as branch and path coverage
```

**Comment by gehrisandro** [comment]
Hm. I am not able to reproduce the issue.

But as your PR seems a reasonable fix, I am going to merge it. Thanks 🎉
